language: scala

jdk:
  - openjdk8

scala:
  - 2.11.12

env:
  matrix:
    - PROFILE=test
    - PROFILE=check

install: true

script:
  - if [ "$PROFILE" = "test" ]; then mvn clean test; fi
  - if [ "$PROFILE" = "check" ]; then mvn clean compile -Dcluster; fi
